### ISSUE TITLE
The alert for missing rogue pieces keeps going off while wearing the full set

### ISSUE THREAD

**Issue by iMxAndyy** [pajlads/runelite-pickpocket-helper#3]
![image](https://github.com/user-attachments/assets/e0a112c1-cfb9-43a5-9daf-9c28544c6f41)

No idea why its doing this. 
but screenshot attached to show what I'm wearing when its alerting me that I'm not wearing the full set

**Comment by DaraTheGreat** [comment]
This seems to have been fixed.
